Description: |
  DeVesco Pierre /Udacity 2020 Training
Parameters:
  EnvironmentName:
    Description: An Environment name that will be prefixed to resources
    Type: String
Resources:
  LBSecGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow http to our load balancer
      VpcId:
        'Fn::ImportValue': !Sub '${EnvironmentName}-VPCID'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 4dd3c839-1307-4666-8e6a-77491f8ff18d
  WebServerSecGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow http to our web hosts and SSH from local only
      VpcId:
        'Fn::ImportValue': !Sub '${EnvironmentName}-VPCID'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 88d0da1f-8da5-4406-99f2-154b53b3a885
  WebAppLaunchConfig:
    Type: 'AWS::AutoScaling::LaunchConfiguration'
    Properties:
      UserData:
        'Fn::Base64': !Sub |
          #!/bin/bash -x

          apt-get -y update
          apt-get -y install apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          add-apt-repository \
           "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
           $(lsb_release -cs) stable"
          apt-get update
          apt-get -y install docker-ce
          usermod -aG docker ubuntu
          docker run -p 8080:8080 tomcat:8.0
      ImageId: ami-005bdb005fb00e791
      KeyName: Cloudformation-ec2
      SecurityGroups:
        - Ref: WebServerSecGroup
      InstanceType: t3.medium
      BlockDeviceMappings:
        - DeviceName: /dev/sdk
          Ebs:
            VolumeSize: '10'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 26a02da6-faa8-4565-a2d4-171c1f3b8878
  WebAppGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      VPCZoneIdentifier:
        - 'Fn::ImportValue': !Sub '${EnvironmentName}-PRIV-NETS'
      LaunchConfigurationName:
        Ref: WebAppLaunchConfig
      MinSize: '3'
      MaxSize: '5'
      TargetGroupARNs:
        - Ref: WebAppTargetGroup
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 5b19e177-7c4d-48e2-b841-97afd083fbfb
  WebAppLB:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Subnets:
        - 'Fn::ImportValue': !Sub '${EnvironmentName}-PUB1-SN'
        - 'Fn::ImportValue': !Sub '${EnvironmentName}-PUB2-SN'
      SecurityGroups:
        - Ref: LBSecGroup
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 1ba37a7b-f964-42dc-a35f-3a4c8ab19d86
  Listener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn:
            Ref: WebAppTargetGroup
      LoadBalancerArn:
        Ref: WebAppLB
      Port: '80'
      Protocol: HTTP
    Metadata:
      'AWS::CloudFormation::Designer':
        id: c7a7c01a-4293-41ee-be61-1447b7a859a1
  ALBListenerRule:
    Type: 'AWS::ElasticLoadBalancingV2::ListenerRule'
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref WebAppTargetGroup
      Conditions:
        - Field: path-pattern
          Values:
            - /
      ListenerArn: !Ref Listener
      Priority: 1
    Metadata:
      'AWS::CloudFormation::Designer':
        id: c70797bc-c004-4312-81ad-493ced114ac4
  WebAppTargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 8
      HealthyThresholdCount: 2
      Port: 8080
      Protocol: HTTP
      UnhealthyThresholdCount: 5
      VpcId:
        'Fn::ImportValue':
          'Fn::Sub': '${EnvironmentName}-VPCID'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: fbddb93c-0732-4ce1-ad91-fd68bc3fb9ef
Metadata:
  'AWS::CloudFormation::Designer':
    fbddb93c-0732-4ce1-ad91-fd68bc3fb9ef:
      size:
        width: 60
        height: 60
      position:
        x: -90
        'y': 100
      z: 1
      embeds: []
    88d0da1f-8da5-4406-99f2-154b53b3a885:
      size:
        width: 60
        height: 60
      position:
        x: 180
        'y': 90
      z: 1
      embeds: []
    26a02da6-faa8-4565-a2d4-171c1f3b8878:
      size:
        width: 60
        height: 60
      position:
        x: -100
        'y': 240
      z: 1
      embeds: []
      isassociatedwith:
        - 88d0da1f-8da5-4406-99f2-154b53b3a885
    5b19e177-7c4d-48e2-b841-97afd083fbfb:
      size:
        width: 60
        height: 60
      position:
        x: 440
        'y': 310
      z: 1
      embeds: []
      isassociatedwith:
        - 26a02da6-faa8-4565-a2d4-171c1f3b8878
        - fbddb93c-0732-4ce1-ad91-fd68bc3fb9ef
    4dd3c839-1307-4666-8e6a-77491f8ff18d:
      size:
        width: 60
        height: 60
      position:
        x: 300
        'y': 90
      z: 1
      embeds: []
    1ba37a7b-f964-42dc-a35f-3a4c8ab19d86:
      size:
        width: 60
        height: 60
      position:
        x: 420
        'y': 210
      z: 1
      embeds: []
      isassociatedwith:
        - 4dd3c839-1307-4666-8e6a-77491f8ff18d
    c7a7c01a-4293-41ee-be61-1447b7a859a1:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 330
      z: 1
      embeds: []
      isassociatedwith:
        - 1ba37a7b-f964-42dc-a35f-3a4c8ab19d86
    c70797bc-c004-4312-81ad-493ced114ac4:
      size:
        width: 60
        height: 60
      position:
        x: 180
        'y': 330
      z: 1
      embeds: []
      isassociatedwith:
        - c7a7c01a-4293-41ee-be61-1447b7a859a1

Outputs:
  LoadBalancerSecurityGroup:
    Description: A reference to the Loadbalancer Security group which allows HTTP Access from the public
    Value: !Ref LBSecGroup
    Export:
      Name: !Sub ${EnvironmentName}-LB-SEC-GROUP

  WebServerSecurityGroup:
    Description: A reference to the WebServer Security Group which is on the private subnet
    Value: !Ref WebServerSecGroup
    Export:
      Name: !Sub ${EnvironmentName}-PRIV-SEC-GROUP

  AutoScaling:
    Description: A reference to the Auto Scaling group which controls cloud roll out. Min 3 servers Max 5
    Value: !Ref WebAppGroup
    Export:
      Name: !Sub ${EnvironmentName}-AUTOSCALING-3-5

  LoadBalancer:
    Description: A reference to the Load Balancer that's used
    Value: !Ref WebAppLB
    Export:
      Name: !Sub ${EnvironmentName}-PRIV-LB